services:
  sementsov-frontend:
    build: .
    container_name: sementsov-frontend
    restart: unless-stopped
    volumes:
      - sementsov-data:/app/data
    networks:
      - pustoshilov-lawyer_default

volumes:
  sementsov-data:

networks:
  pustoshilov-lawyer_default:
    external: true
